# Generated by Django 6.0.7 on 2026-07-27 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('weight_kg', models.FloatField(help_text='Weight in kilograms')),
                ('height_cm', models.FloatField(help_text='Height in centimeters')),
                ('goal', models.CharField(choices=[('lose', 'Lose Weight'), ('maintain', 'Maintain Weight'), ('gain', 'Gain Weight')], default='maintain', max_length=10)),
                ('swallow_preference', models.CharField(choices=[('swallow', 'Swallow'), ('rice', 'Rice based'), ('yam', 'Yam based'), ('both', 'Both')], default='both', max_length=10)),
                ('spice_level', models.CharField(choices=[('mild', 'Mild'), ('medium', 'Medium'), ('very_spicy', 'Very Spicy')], default='medium', max_length=15)),
                ('protein_preference', models.CharField(choices=[('chicken', 'Chicken'), ('fish', 'Fish'), ('beef', 'Beef'), ('turkey', 'Turkey'), ('none', 'No meat (vegetarian)')], default='chicken', max_length=10)),
                ('cultural_region', models.CharField(choices=[('yoruba', 'Yoruba'), ('igbo', 'Igbo'), ('hausa', 'Hausa'), ('general', 'General / No Preference')], default='general', max_length=10)),
                ('budget_level', models.CharField(choices=[('budget', 'Budget friendly (under N5000)'), ('moderate', 'Moderate (N5000 - N15000)'), ('flexible', 'Flexible (above N15000)')], default='moderate', max_length=10)),
                ('allergy_gluten', models.BooleanField(default=False)),
                ('allergy_nuts', models.BooleanField(default=False)),
                ('allergy_fish', models.BooleanField(default=False)),
                ('allergy_eggs', models.BooleanField(default=False)),
                ('allergy_dairy', models.BooleanField(default=False)),
                ('allergy_soy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
